yelb-ui:
  image:
    repository: ghcr.io/vaishnavi639/yelb-ui
    tag: 2bb613e445f53633c2f5655e666ba5945d04f946
  replicas: 1
yelb-appserver:
  image:
    repository: ghcr.io/vaishnavi639/yelb-appserver
    tag: 1290057a89d9ddf2e94df6ab9e1f99b2bfbc4303
  replicas: 1
redis-server:
  image: redis:6.0.9
yelb-db:
  image: mreferre/yelb-db:0.6
