yelb-ui:
  image:
    repository: ghcr.io/vaishnavi639/yelb-ui
    tag: 1f47d68084229177d304b46c017fc6c94252a0ec
  replicas: 2
yelb-appserver:
  image:
    repository: ghcr.io/vaishnavi639/yelb-appserver
    tag: 1290057a89d9ddf2e94df6ab9e1f99b2bfbc4303
  replicas: 1
redis-server:
  image: redis:6.0.9
yelb-db:
  image: mreferre/yelb-db:0.6
