apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-appserver
spec:
  replicas: {{ .Values.yelb-appserver.replicas }}
  selector:
    matchLabels:
      app: yelb-appserver
  template:
    metadata:
      labels:
        app: yelb-appserver
    spec:
      containers:
        - name: yelb-appserver
          image: "{{ .Values.yelb-appserver.image.repository }}:{{ .Values.yelb-appserver.image.tag }}"
          ports:
            - containerPort: 4567
          env:
            - name: EP_DB
              value: "yelb-db"
            - name: EP_REDIS
              value: "redis-server"