apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-appserver
spec:
  replicas: {{ (index .Values "yelb-appserver").replicas }}
  selector:
    matchLabels:
      app: yelb-appserver
  template:
    metadata:
      labels:
        app: yelb-appserver
    spec:
      containers:
        - name: yelb-appserver
          image: "{{ (index .Values "yelb-appserver").image.repository }}:{{ (index .Values "yelb-appserver").image.tag }}"
          ports:
            - containerPort: 4567
          env:
            - name: EP_DB
              value: "yelb-db"
            - name: EP_REDIS
              value: "redis-server"
