apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-ui
spec:
  replicas: {{ (index .Values "yelb-ui").replicas }}
  selector:
    matchLabels:
      app: yelb-ui
  template:
    metadata:
      labels:
        app: yelb-ui
    spec:
      containers:
        - name: yelb-ui
          image: "{{ (index .Values "yelb-ui").image.repository }}:{{ (index .Values "yelb-ui").image.tag }}"
          ports:
            - containerPort: 80
